### ISSUE TITLE
the "!command add" command creates a command with an empty name if you put a double space before the command name.

### ISSUE THREAD

**Issue by Thelonedevil** [OTBProject/OTBScripts#10]
If you do the following: "!addcom  !poke anything" (note the souble space between '!addcom' and '!poke') it adds the command with no name to the database, this makes it impossible to remove via chat.

**Comment by NthPortal** [comment]
Actually a problem with how commands are processed, not with the script.

**Comment by NthPortal** [comment]
See https://github.com/OTBProject/OTBProject/issues/121 on OTBProject.
